apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-policy
spec:
  template:
    spec:
      containers:
      - name: mixer
        image: "docker.io/istio/mixer:0.8.0"
      - name: istio-proxy
        image: "docker.io/istio/proxyv2:0.8.0"