apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-sidecar-injector
spec:
  template:
    spec:
      containers:
      - name: sidecar-injector-webhook
        image: "docker.io/istio/sidecar_injector:0.8.0"