apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-egressgateway
spec:
  template:
    spec:
      containers:
      - name: egressgateway
        image: "alekssaul/istio/proxyv2:0.8.0"