apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-pilot
spec:
  template:
    spec:
      containers:
      - name: discovery
        image: "docker.io/istio/pilot:0.8.0"
      - name: istio-proxy
        image: "docker.io/istio/proxyv2:0.8.0"