apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ingressgateway
spec:
  template:
    spec:
      containers:
      - name: ingressgateway
        image: "docker.io/istio/proxyv2:0.8.0"